### ISSUE TITLE
media_player.play_media / tts.speak fails: module 'reolink_aio.baichuan.xmls' has no attribute 'XML_HEADER' (HA 2026.9.x)

### ISSUE THREAD

**Issue by azisten** [joeblack2k/reolink_talk#7]
### Problem
After updating Home Assistant from 2026.8.3 to 2026.9.3, sending TTS (or any audio) to a Reolink Talk media player fails with:

    media_player/play_media failed: module 'reolink_aio.baichuan.xmls' has no attribute 'XML_HEADER'

In the UI, calling `tts.speak` (Piper) with the Reolink Talk media player as target only shows "Unknown error"; the actual cause is the AttributeError above.

### Cause
`custom_components/reolink_talk/talk.py` (around line 560) builds the talk extension XML with `xmls.XML_HEADER`:

    ext = (
        xmls.XML_HEADER
        + '<Extension version="1.1">\n'
        ...

The newer `reolink_aio` shipped with HA core no longer has that constant. According to the reolink_aio 0.21.17 release notes, XML_HEADER concatenation was replaced by `xml_declaration`, and HA core bumped reolink_aio to 0.21.17 (home-assistant/core#182472).

### Environment
- Home Assistant: 2026.9.3 (HAOS, VM)
- ha-reolink-talk: v1.1.5 (installed via HACS)
- reolink_aio: 
- Last working: HA 2026.8.3

### Workaround proposal
Replacing `xmls.XML_HEADER` with a fallback works for me on both old and new library versions:

    getattr(xmls, "XML_HEADER", '<?xml version="1.0" encoding="UTF-8" ?>\n')

### Suggestion
Don't rely on `xmls.XML_HEADER`; define the XML declaration string locally in the integration, so it no longer depends on reolink_aio internals.
